### ISSUE TITLE
Add search function

### ISSUE THREAD

**Issue by TinsFox** [ghostty-org/website#161]
There is no search function now, which is a bit troublesome to find the configuration.

**Comment by shortcuts** [comment]
Hey, I've opened a discussion here https://github.com/ghostty-org/ghostty/discussions/3195 for that matter

**Comment by BrandonRomano** [comment]
Thank you @TinsFox for opening this thread & @shortcuts for creating a discussion.

We'll talk on the discussion & then open up a ticket here once we've aligned on the approach.
