### ISSUE TITLE
Tab bar gets transparent

### ISSUE THREAD

**Issue by horyekhunley** [ghostty-org/website#188]
![Image](https://github.com/user-attachments/assets/f0e777be-6cd6-4248-9aef-64c17bf698b3)
when i create a new tab, my tab bar becomes transparent. I am on cachyos
Also, how do I make tmux persistent in my terminal, I use the keyword "shell" to define the path to my tmux on kitty.
This is my config:
theme = catppuccin-mocha
background-opacity = 0.95

#shell = /home/linuxbrew/.linuxbrew/bin/tmux

gtk-titlebar = false
cursor-style = block
mouse-hide-while-typing = true
# macos-titlebar-style = hidden
window-padding-balance = true
window-save-state = always
window-colorspace = "display-p3"

font-family = MesloLGS Nerd Font Mono
font-size = 16

**Comment by BrandonRomano** [comment]
Hey @horyekhunley; you're in the Website repo here (the code that runs https://ghostty.org/).

Check out the contributing guide to see how to report a bug if you found one!
https://github.com/ghostty-org/ghostty/blob/main/CONTRIBUTING.md
