### ISSUE TITLE
Add explicit examples for each option

### ISSUE THREAD

**Issue by jsumners** [ghostty-org/website#200]
The docs are quite good. But it would be very helpful if each option included a literal example of what it would look like in a config file. [`font-family`](https://ghostty.org/docs/config/reference#font-family) does a good job at this, but [`background`](https://ghostty.org/docs/config/reference#background) (and `foreground`) require some intuition to understand.

In short, it would be helpful if each configuration option had a real copy and paste-able example.

**Comment by BrandonRomano** [comment]
Hey @jsumners 👋 would you mind opening a [discussion](https://github.com/ghostty-org/ghostty/discussions) for this here?  issues aren't the right place for this request.

https://github.com/ghostty-org/website/blob/main/CONTRIBUTING.md

**Comment by jsumners** [comment]
I don't understand that decision. The website is the thing that needs updating.

**Comment by mitchellh** [comment]
See CONTRIBUTING.md. Keeping things in one place helps us triage in one place
