### ISSUE TITLE
Google still not picking up favicon

### ISSUE THREAD

**Issue by BrandonRomano** [ghostty-org/website#206]
This could be an issue with indexing, but it looks like the favicon is still not showing up in search.

https://developers.google.com/search/docs/appearance/favicon-in-search

![Image](https://github.com/user-attachments/assets/1d81505a-e249-462f-bf7e-b73d55457edb)

**Comment by arithefirst** [comment]
I did a little bit of reading and found [this](https://developers.google.com/search/docs/appearance/favicon-in-search) article by Google. The most likely reasons, from what I can tell, are:

- Google is not allowed to crawl the images for some reason
- Something is weird with the icon's path or sizing

The only thing I can think of at the moment that _might_ fix this would be moving the `<link rel="shortcut icon" href="/favicon.ico">` to the top of the `<head>` so it's the first thing the indexer sees.

**Comment by BrandonRomano** [comment]
I would be quite surprised if it were the ordering of the content in the head; but who knows google works in mysterious ways sometimes.

Yeah the loose ideas I have here:
- We have multiple `<link rel="icon"...` for different sizes
- One is `<link rel="shortcut icon" href="/favicon.ico" />` (I'm not sure if `shortcut` is messing with Google at all)
- We're using relative links (according to the docs, that is OK, but sometimes relative links mess up; so maybe switching to https://ghostty.org/favicon.ico might fix it

**Comment by arithefirst** [comment]
I don't it's the shortcut icon syntax, as Google says they support it

**Comment by ronit18** [comment]
Google has picked up the ico. this has been fixed now

 <img width="984" alt="Image" src="https://github.com/user-attachments/assets/74f05a98-ff8b-4d7d-93b7-b946bdd5fe6b" />

**Comment by arithefirst** [comment]
Oh cool! Sometimes you just have to wait a while for Google to index icons.
